# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/image_test/image_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test || ORIG_REF_NAME==image_test} -quiet] -quiet

# IP: bd/image_test/ip/image_test_processing_system7_0_0/image_test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_processing_system7_0_0 || ORIG_REF_NAME==image_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/image_test/ip/image_test_inverter_0_0/image_test_inverter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_inverter_0_0 || ORIG_REF_NAME==image_test_inverter_0_0} -quiet] -quiet

# IP: bd/image_test/ip/image_test_axi_dma_0_0/image_test_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_axi_dma_0_0 || ORIG_REF_NAME==image_test_axi_dma_0_0} -quiet] -quiet

# IP: bd/image_test/ip/image_test_ps7_0_axi_periph_0/image_test_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==image_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/image_test/ip/image_test_rst_ps7_0_100M_0/image_test_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==image_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/image_test/ip/image_test_axi_smc_0/image_test_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_axi_smc_0 || ORIG_REF_NAME==image_test_axi_smc_0} -quiet] -quiet

# IP: bd/image_test/ip/image_test_system_ila_0_0/image_test_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_system_ila_0_0 || ORIG_REF_NAME==image_test_system_ila_0_0} -quiet] -quiet

# IP: bd/image_test/ip/image_test_auto_pc_0/image_test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_test_auto_pc_0 || ORIG_REF_NAME==image_test_auto_pc_0} -quiet] -quiet

# XDC: bd/image_test/image_test_ooc.xdc
